openapi: 3.1.0
info:
  title: Parallel API
  description: Parallel API
  contact:
    name: Parallel Support
    url: https://parallel.ai
    email: support@parallel.ai
  version: 0.1.2
servers:
  - url: https://api.parallel.ai
    description: Parallel API
paths:
  /v1beta/tasks/groups:
    post:
      tags:
        - Task API (Beta)
      summary: Create a task group for batch processing
      description: >-
        Creates a new TaskGroup container to organize and track multiple task
        runs collectively. Task Groups enable efficient batch processing of
        hundreds or thousands of tasks with unified monitoring, intelligent
        failure handling, and real-time results streaming. This is ideal for
        large-scale operations like bulk CRM enrichment, due diligence
        workflows, or competitive intelligence gathering where you need to
        process many similar tasks and monitor their progress as a group.
      operationId: tasks_taskgroups_post_v1beta_tasks_groups_post
      requestBody:
        content:
          application/json:
            schema:
              properties:
                metadata:
                  anyOf:
                    - additionalProperties:
                        anyOf:
                          - type: string
                          - type: integer
                          - type: number
                          - type: boolean
                      type: object
                    - type: 'null'
                  title: Metadata
                  description: User-provided metadata stored with the task group.
              type: object
              title: CreateTaskGroupRequest
              description: Request to create a task group.
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                properties:
                  taskgroup_id:
                    type: string
                    title: Taskgroup Id
                    description: ID of the group.
                  metadata:
                    anyOf:
                      - additionalProperties:
                          anyOf:
                            - type: string
                            - type: integer
                            - type: number
                            - type: boolean
                        type: object
                      - type: 'null'
                    title: Metadata
                    description: User-provided metadata stored with the group.
                  status:
                    allOf:
                      - properties:
                          num_task_runs:
                            type: integer
                            title: Num Task Runs
                            description: Number of task runs in the group.
                          task_run_status_counts:
                            additionalProperties:
                              type: integer
                            type: object
                            title: Task Run Status Counts
                            description: Number of task runs with each status.
                          is_active:
                            type: boolean
                            title: Is Active
                            description: >-
                              True if at least one run in the group is currently
                              active, i.e. status is one of {'cancelling',
                              'queued', 'running'}.
                          status_message:
                            anyOf:
                              - type: string
                              - type: 'null'
                            title: Status Message
                            description: Human-readable status message for the group.
                          modified_at:
                            anyOf:
                              - type: string
                              - type: 'null'
                            title: Modified At
                            description: >-
                              Timestamp of the last status update to the group,
                              as an RFC 3339 string.
                            examples:
                              - '2025-04-24T18:56:22.513132Z'
                        type: object
                        required:
                          - num_task_runs
                          - task_run_status_counts
                          - is_active
                          - status_message
                          - modified_at
                        title: TaskGroupStatus
                        description: Status of a task group.
                    description: Status of the group.
                  created_at:
                    anyOf:
                      - type: string
                      - type: 'null'
                    title: Created At
                    description: >-
                      Timestamp of the creation of the group, as an RFC 3339
                      string.
                    examples:
                      - '2025-04-24T18:56:22.513132Z'
                type: object
                required:
                  - taskgroup_id
                  - status
                  - created_at
                title: TaskGroupResponse
                description: >-
                  Response object for a task group, including its status and
                  metadata.
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                properties:
                  detail:
                    items:
                      properties:
                        loc:
                          items:
                            anyOf:
                              - type: string
                              - type: integer
                          type: array
                          title: Location
                        msg:
                          type: string
                          title: Message
                        type:
                          type: string
                          title: Error Type
                      type: object
                      required:
                        - loc
                        - msg
                        - type
                      title: ValidationError
                    type: array
                    title: Detail
                type: object
                title: HTTPValidationError
